### ISSUE TITLE
read_only function should also prevent field from populating the data

### ISSUE THREAD

**Issue by quantus** [kvesteri/wtforms-components#32]
I am trying to create a form with some fields that should not be writable by the user. By using `read_only` function the html side works as expected, but it seems that the field still populates the data when `form.populate_obj` is called. I can't see any case where we would like to have html side say that the field is read_only but still save the changes that the user has made to that field. Therefore I would expect that calling `read_only` to a field also disables populating of that field during `form.populate_obj` function call.

My current workaround is to manually remove all read_only fields from the form before calling `form.populate_obj`.

**Comment by tvuotila** [comment]
This is interesting case. Read only field literally means that a new value can not be written to the field. If the value of the field is set to something, nothing should change it afterwards. One example where it might be used:

```
class CreateUserForm(Form):
    email = StringField()
    role = StringField()
``` 
You want to user to have `user.role = 'customer'`. So you write following (or something similar):
```
form = CreateUserForm()
form.role.data = 'customer'
```
You don't want to allow user changing the field, so you set it "read only" after creating the form:
```
read_only(form.role)
``` 
You process and validate the form.
```
form.process(formdata, user)
if not form.validate():
    # Process error case
```
Finally you populate the object
```
form.populate_obj(user)
```
Naturally, you want the following to be true `user.role == 'customer'`, which requires that the value is populated to the object.



The problem with above is that usually form and object data is given at form creation `CreateUserForm(formdata, user)`. This is also the style [WTForms examples](http://wtforms.readthedocs.org/en/latest/crash_course.html#using-forms) use. `read_only` function can only be applied to fields which are bound to form. By the time field is bound, it has populated itself based on form and object data. By definition `read_only` should leave values of these populated fields as they were before they were made read only.



I am worried that extending functionality of `read_only` to prevent population of data to object would create a risk of confusion.

I can think of two possible solutions:
 1. Fix `read_only` to prevent the population of field data to object.
 2. We create new function `dont_populate(field)` and fix `read_only` to freeze the data.

**Comment by tvuotila** [comment]
Changes are quite trivial. Preventing the change of read only field with `process` fd71fb7 and preventing the `populate_obj` to populate the object  58473d2.

**Comment by tvuotila** [comment]
@kvesteri I would like you to decide how we proceed.

**Comment by kvesteri** [comment]
I think read_only should monkeypatch the process and population as suggested. I would rename the 'noop' function to 'do_nothing' though.
