### ISSUE TITLE
Unique validator, what is `form._obj`?

### ISSUE THREAD

**Issue by timgame** [kvesteri/wtforms-components#34]
https://github.com/kvesteri/wtforms-components/blob/80284f920dd7432a27e43695a370901c8305bd8f/wtforms_components/validators.py#L242
I'm using the `Unique` validator from `wtforms_components` directly. What is `from._obj`? I'ts not a attribute of my form which inherits from `flask_wtf.Form`. Replacing the line linked above by `if obj:` fixes the problem for me. It's also misleading to raise an `ValidationError` in case the `_obj` attribute is not set. You should rather raise a different Exception.

**Comment by tvuotila** [comment]
What if form edits an existing object? `form._obj` is needed for finding out the object currently being edited.

As in [documentation example](http://wtforms-components.readthedocs.org/en/latest/index.html#unique-validator) you should inherit your form from [ModelForm](https://github.com/kvesteri/wtforms-components/blob/80284f920dd7432a27e43695a370901c8305bd8f/wtforms_components/__init__.py#L71). That way you have the `form._obj` set in `def __init__`. I think this could be emphasized more.

I agree that raising an `ValidationError` when `hasattr(form, '_obj') == False` is misleading. I am not sure if we could just ignore it and agree that objects can not be edited with a form missing the attribute.

**Comment by timgame** [comment]
Thanks for your explanation and effort! In case the repo administrator wouldn't like the approach of allowing to omit the `_obj` attribute I would be totally fine with a different explanatory exception.

**Comment by kvesteri** [comment]
Now fixed.
