### ISSUE TITLE
WTForms=2.1 removes wtforms.ext.sqlalchemy

### ISSUE THREAD

**Issue by tanj** [kvesteri/wtforms-components#36]
wtforms_components/fields/ajax.py imports from wtforms.ext.sqlalchemy and fails with the latest version of wtforms.

See Commit:
https://github.com/wtforms/wtforms/commit/c49ecfb7e76f919eafb5c6a11c3b795c4e613757

ImportError
c:\python27\lib\site-packages\wtforms_components\fields\ajax.py in <module>()
      4 import six
      5 from wtforms import fields, widgets
----> 6 from wtforms.ext.sqlalchemy.fields import get_pk_from_identity
      7 from wtforms.validators import ValidationError
      8

**Comment by kvesteri** [comment]
Now fixed.
