### ISSUE TITLE
No PhoneNumberField in 0.10.0 release

### ISSUE THREAD

**Issue by brandones** [kvesteri/wtforms-components#39]
```
  File "/Users/bistenes/Code/webthing/src/application/forms.py", line 16, in <module>
    from wtforms_components import PhoneNumberField
ImportError: cannot import name PhoneNumberField
```

Works fine up until 0.9.9.

**Comment by hyperknot** [comment]
This one is very serious, as `wtforms_alchemy` depends on `wtforms-components`, and now every `wtforms_alchemy` install is broken, unless manually pinning down the components dependency!

**Comment by kvesteri** [comment]
Released new version of WTForms-Alchemy. Now WTForms-Alchemy contains all SQLAlchemy-dependent fields (for example PhoneNumberField).

**Comment by hyperknot** [comment]
@kvesteri I'd kindly ask you to please synchronise such releases in the future by changing the dependencies before and after release. If anyone has every deployed a server with a pip install yesterday it ended up in a broken state.

What could have been a solution is to:
- change alchemy to components<0.10, release an old alchemy with updated dependency
- release components 0.10
- release new alchemy with components >= 0.10

**Comment by brandones** [comment]
It would also be cool to give clients of your code a little warning in the future.
https://wiki.python.org/moin/PythonDecoratorLibrary#Generating_Deprecation_Warnings

**Comment by kvesteri** [comment]
Duly noted and I'm sorry for all the hassle this caused.

**Comment by dappiu** [comment]
_PhoneNumberType_ is still present in _WTForms-Components_ documentation, but missing in the code. For what I understand, _PhoneNumberType_ was moved permanently on _WTForms-Alchemy_ package, right?
