### ISSUE TITLE
The "Unique" validator is no longer present?

### ISSUE THREAD

**Issue by rgeos** [kvesteri/wtforms-components#54]
In the latest documentation [Unique Validator](https://wtforms-components.readthedocs.io/en/latest/#unique-validator) is presented as a way for checking the unicity of given field in database.
A quick check of the [source code](https://github.com/kvesteri/wtforms-components/blob/master/wtforms_components/validators.py) shows no sign of  the **Unique** class. 
I can't figure out how this works. Can someone give me an example?
Thank you!

**Comment by kvesteri** [comment]
The unique validator was removed since it requires SQLAlchemy dependency. It is now part of WTForms-Alchemy package.

**Comment by rmews** [comment]
What version was the Unique class removed from?

**Comment by kvesteri** [comment]
I updated the docs. The Unique validator was moved to WTForms-Alchemy as of version 0.10.0 due to it's SQLAlchemy dependency.
