### ISSUE TITLE
Adapt to WTForms version 2.3

### ISSUE THREAD

**Issue by DadaDaMotha** [kvesteri/wtforms-components#66]
There are changes in the new [WTForms version 2.3](https://github.com/wtforms/wtforms/blob/master/CHANGES.rst#version-230) that break the code. The removing of `HTMLField` leads to import errors.
Thanks four you engagement!

**Comment by ArunVenkata** [comment]
Do Check Issue #67 . Is that similar to the import error you seem to have?

**Comment by DadaDaMotha** [comment]
Yes, #67 is what I described above.
