### ISSUE TITLE
error while using WTForms-Components==0.10.4

### ISSUE THREAD

**Issue by ArunVenkata** [kvesteri/wtforms-components#67]
![image](https://user-images.githubusercontent.com/19998416/79990520-c6b37300-84ce-11ea-9cce-f8004aa20de0.png)

I installed WTForms-Components==0.10.4 and it gives an error while running my flask application. 
I am also installing WTForms-Alchemy==0.16.9 and Flask-WTF==0.14.2.

check the logs in the picture.
the top line is code inside my file and the rest are all inside the package files

The error seems to occur inside one of the wtform core files. This is something i noticed just a few hours ago and did not occur before. Could it be some version incompatibility issue? 

I also found a pull request which removes the HTMLString from the code here https://github.com/wtforms/wtforms/pull/400

**Comment by larsderidder** [comment]
WTForms was updated to 2.3.0 today. WTForms-Components depends on 'WTForms>=1.0.4', so we get the latest issue.

A quick fix is to pin the version of WTForms to 2.2.1 in your requirements.txt (or do `pip install WTForms==2.2.1`).
